/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.13.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtQuickWidgets/QQuickWidget>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTabWidget *tabWidget;
    QWidget *tab;
    QQuickWidget *quickWidget;
    QPushButton *clearMap;
    QLabel *errorLabel;
    QPushButton *addMarkers;
    QPushButton *addEdges;
    QTabWidget *tabWidget_2;
    QWidget *stadiumInfoTab;
    QLabel *stadiumInfoLabel;
    QComboBox *stadiumListDropDown;
    QListWidget *stadiumList;
    QWidget *tripsTab;
    QLabel *planTripLabel;
    QListWidget *itinerary;
    QLabel *itineraryLabel;
    QTabWidget *tabWidget_3;
    QWidget *presetTab;
    QPushButton *displayMajorLeagueTrip;
    QLabel *whereDoYouWantToGoLabel;
    QPushButton *displayNationalLeagueTrip;
    QPushButton *displayAmericanLeagueTrip;
    QPushButton *safecoButton;
    QWidget *planATripTab;
    QPushButton *letsTravel;
    QLabel *chooseDestinationsLabel;
    QLabel *destinationsListLabel;
    QListWidget *chooseDestinationsList;
    QListWidget *destinationList;
    QPushButton *addStadiumToTrip;
    QPushButton *clearDestinationList;
    QLabel *planATripErrorLabel;
    QWidget *findDistanceTab;
    QLabel *label_22;
    QListWidget *findDistA;
    QLabel *label_23;
    QListWidget *findDistB;
    QLabel *label_24;
    QPushButton *distanceButton;
    QLabel *distanceLabel;
    QWidget *souvenirsTab;
    QTableWidget *souvenirsTable;
    QLabel *label_7;
    QLabel *totalPurchaseLabel;
    QLabel *totalPurchasePriceLabel;
    QLabel *label_8;
    QListWidget *makePurchaseList;
    QPushButton *purchaseButton;
    QLabel *souvenirsErrorLabel;
    QWidget *tab_3;
    QPushButton *randomButton;
    QListWidget *randomDisplay;
    QLabel *label_25;
    QPushButton *redEdges;
    QPushButton *singleEdge;
    QWidget *tab_2;
    QLabel *addTeamStadiumLabel;
    QLabel *modifySouvenirLabel;
    QFrame *line_2;
    QLineEdit *passwordBox;
    QLabel *enterPassLabel;
    QFrame *line_3;
    QFrame *line_4;
    QLineEdit *teamNameBox;
    QLineEdit *stadiumBox;
    QDateEdit *openDateBox;
    QLabel *label;
    QLabel *label_2;
    QLabel *modifyStadiumInfoLabel;
    QComboBox *modifyTeamList;
    QListWidget *adminStadiumInfo;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_9;
    QLineEdit *addressBox;
    QLabel *label_10;
    QLineEdit *cityBox;
    QLabel *label_11;
    QLineEdit *stateBox;
    QSpinBox *capacityBox;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *latitudeBox;
    QLabel *label_15;
    QLineEdit *longitudeBox;
    QLineEdit *zipBox;
    QLabel *label_16;
    QPushButton *adminAddBox;
    QRadioButton *americanToggle;
    QRadioButton *nationalToggle;
    QLabel *label_17;
    QComboBox *grassBox;
    QPushButton *modifyButton;
    QLabel *label_18;
    QLineEdit *phoneBox;
    QComboBox *modifySouvenirList;
    QLabel *label_19;
    QLabel *label_20;
    QLineEdit *souvNameBox;
    QDoubleSpinBox *souvPriceBox;
    QLabel *label_21;
    QPushButton *modifySouvButton;
    QPushButton *addSouvButton;
    QPushButton *deleteSouvButton;
    QLabel *adminPassError;
    QCheckBox *canadaBox;
    QLabel *adminStadiumError;
    QLabel *adminSouvError;
    QMenuBar *menuBar;
    QMenu *menuI_Love_Baseball;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1809, 975);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(10, 18, 1751, 891));
        QFont font;
        font.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font.setPointSize(8);
        tabWidget->setFont(font);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        quickWidget = new QQuickWidget(tab);
        quickWidget->setObjectName(QString::fromUtf8("quickWidget"));
        quickWidget->setGeometry(QRect(30, 20, 1031, 791));
        quickWidget->setResizeMode(QQuickWidget::SizeRootObjectToView);
        quickWidget->setSource(QUrl(QString::fromUtf8("qrc:/qml/testQML.qml")));
        clearMap = new QPushButton(tab);
        clearMap->setObjectName(QString::fromUtf8("clearMap"));
        clearMap->setGeometry(QRect(980, 820, 80, 25));
        errorLabel = new QLabel(tab);
        errorLabel->setObjectName(QString::fromUtf8("errorLabel"));
        errorLabel->setGeometry(QRect(34, 819, 541, 21));
        addMarkers = new QPushButton(tab);
        addMarkers->setObjectName(QString::fromUtf8("addMarkers"));
        addMarkers->setEnabled(true);
        addMarkers->setGeometry(QRect(620, 820, 80, 25));
        addMarkers->setFlat(false);
        addEdges = new QPushButton(tab);
        addEdges->setObjectName(QString::fromUtf8("addEdges"));
        addEdges->setGeometry(QRect(710, 820, 80, 25));
        tabWidget_2 = new QTabWidget(tab);
        tabWidget_2->setObjectName(QString::fromUtf8("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(1110, 20, 591, 811));
        stadiumInfoTab = new QWidget();
        stadiumInfoTab->setObjectName(QString::fromUtf8("stadiumInfoTab"));
        stadiumInfoLabel = new QLabel(stadiumInfoTab);
        stadiumInfoLabel->setObjectName(QString::fromUtf8("stadiumInfoLabel"));
        stadiumInfoLabel->setGeometry(QRect(30, 20, 161, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Fixedsys"));
        font1.setPointSize(12);
        stadiumInfoLabel->setFont(font1);
        stadiumListDropDown = new QComboBox(stadiumInfoTab);
        stadiumListDropDown->setObjectName(QString::fromUtf8("stadiumListDropDown"));
        stadiumListDropDown->setGeometry(QRect(30, 50, 511, 31));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Fixedsys"));
        font2.setPointSize(9);
        stadiumListDropDown->setFont(font2);
        stadiumList = new QListWidget(stadiumInfoTab);
        stadiumList->setObjectName(QString::fromUtf8("stadiumList"));
        stadiumList->setGeometry(QRect(30, 90, 511, 651));
        tabWidget_2->addTab(stadiumInfoTab, QString());
        tripsTab = new QWidget();
        tripsTab->setObjectName(QString::fromUtf8("tripsTab"));
        planTripLabel = new QLabel(tripsTab);
        planTripLabel->setObjectName(QString::fromUtf8("planTripLabel"));
        planTripLabel->setGeometry(QRect(30, 420, 231, 20));
        planTripLabel->setFont(font1);
        itinerary = new QListWidget(tripsTab);
        itinerary->setObjectName(QString::fromUtf8("itinerary"));
        itinerary->setGeometry(QRect(30, 60, 531, 341));
        QFont font3;
        font3.setPointSize(10);
        itinerary->setFont(font3);
        itineraryLabel = new QLabel(tripsTab);
        itineraryLabel->setObjectName(QString::fromUtf8("itineraryLabel"));
        itineraryLabel->setGeometry(QRect(30, 30, 111, 16));
        itineraryLabel->setFont(font1);
        tabWidget_3 = new QTabWidget(tripsTab);
        tabWidget_3->setObjectName(QString::fromUtf8("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(20, 440, 541, 311));
        presetTab = new QWidget();
        presetTab->setObjectName(QString::fromUtf8("presetTab"));
        displayMajorLeagueTrip = new QPushButton(presetTab);
        displayMajorLeagueTrip->setObjectName(QString::fromUtf8("displayMajorLeagueTrip"));
        displayMajorLeagueTrip->setGeometry(QRect(30, 100, 391, 25));
        displayMajorLeagueTrip->setFont(font2);
        whereDoYouWantToGoLabel = new QLabel(presetTab);
        whereDoYouWantToGoLabel->setObjectName(QString::fromUtf8("whereDoYouWantToGoLabel"));
        whereDoYouWantToGoLabel->setGeometry(QRect(30, 50, 221, 16));
        whereDoYouWantToGoLabel->setFont(font2);
        displayNationalLeagueTrip = new QPushButton(presetTab);
        displayNationalLeagueTrip->setObjectName(QString::fromUtf8("displayNationalLeagueTrip"));
        displayNationalLeagueTrip->setGeometry(QRect(30, 140, 471, 25));
        displayNationalLeagueTrip->setFont(font2);
        displayAmericanLeagueTrip = new QPushButton(presetTab);
        displayAmericanLeagueTrip->setObjectName(QString::fromUtf8("displayAmericanLeagueTrip"));
        displayAmericanLeagueTrip->setGeometry(QRect(30, 180, 471, 25));
        displayAmericanLeagueTrip->setFont(font2);
        safecoButton = new QPushButton(presetTab);
        safecoButton->setObjectName(QString::fromUtf8("safecoButton"));
        safecoButton->setGeometry(QRect(430, 100, 71, 25));
        safecoButton->setFont(font2);
        tabWidget_3->addTab(presetTab, QString());
        planATripTab = new QWidget();
        planATripTab->setObjectName(QString::fromUtf8("planATripTab"));
        letsTravel = new QPushButton(planATripTab);
        letsTravel->setObjectName(QString::fromUtf8("letsTravel"));
        letsTravel->setGeometry(QRect(280, 210, 241, 41));
        letsTravel->setFont(font1);
        chooseDestinationsLabel = new QLabel(planATripTab);
        chooseDestinationsLabel->setObjectName(QString::fromUtf8("chooseDestinationsLabel"));
        chooseDestinationsLabel->setGeometry(QRect(20, 20, 261, 20));
        chooseDestinationsLabel->setFont(font2);
        destinationsListLabel = new QLabel(planATripTab);
        destinationsListLabel->setObjectName(QString::fromUtf8("destinationsListLabel"));
        destinationsListLabel->setGeometry(QRect(280, 20, 191, 16));
        destinationsListLabel->setFont(font2);
        chooseDestinationsList = new QListWidget(planATripTab);
        chooseDestinationsList->setObjectName(QString::fromUtf8("chooseDestinationsList"));
        chooseDestinationsList->setGeometry(QRect(20, 40, 231, 161));
        destinationList = new QListWidget(planATripTab);
        destinationList->setObjectName(QString::fromUtf8("destinationList"));
        destinationList->setGeometry(QRect(280, 40, 241, 161));
        addStadiumToTrip = new QPushButton(planATripTab);
        addStadiumToTrip->setObjectName(QString::fromUtf8("addStadiumToTrip"));
        addStadiumToTrip->setGeometry(QRect(20, 210, 231, 25));
        addStadiumToTrip->setFont(font2);
        clearDestinationList = new QPushButton(planATripTab);
        clearDestinationList->setObjectName(QString::fromUtf8("clearDestinationList"));
        clearDestinationList->setGeometry(QRect(20, 240, 231, 25));
        clearDestinationList->setFont(font2);
        planATripErrorLabel = new QLabel(planATripTab);
        planATripErrorLabel->setObjectName(QString::fromUtf8("planATripErrorLabel"));
        planATripErrorLabel->setGeometry(QRect(280, 257, 241, 16));
        tabWidget_3->addTab(planATripTab, QString());
        findDistanceTab = new QWidget();
        findDistanceTab->setObjectName(QString::fromUtf8("findDistanceTab"));
        label_22 = new QLabel(findDistanceTab);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(10, 10, 201, 16));
        label_22->setFont(font2);
        findDistA = new QListWidget(findDistanceTab);
        findDistA->setObjectName(QString::fromUtf8("findDistA"));
        findDistA->setGeometry(QRect(40, 60, 221, 151));
        label_23 = new QLabel(findDistanceTab);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(108, 40, 81, 16));
        label_23->setFont(font2);
        findDistB = new QListWidget(findDistanceTab);
        findDistB->setObjectName(QString::fromUtf8("findDistB"));
        findDistB->setGeometry(QRect(280, 60, 221, 151));
        label_24 = new QLabel(findDistanceTab);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(350, 40, 81, 16));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Fixedsys"));
        font4.setPointSize(5);
        label_24->setFont(font4);
        distanceButton = new QPushButton(findDistanceTab);
        distanceButton->setObjectName(QString::fromUtf8("distanceButton"));
        distanceButton->setGeometry(QRect(200, 220, 161, 41));
        distanceButton->setFont(font1);
        distanceLabel = new QLabel(findDistanceTab);
        distanceLabel->setObjectName(QString::fromUtf8("distanceLabel"));
        distanceLabel->setGeometry(QRect(320, 220, 141, 41));
        QFont font5;
        font5.setPointSize(16);
        distanceLabel->setFont(font5);
        tabWidget_3->addTab(findDistanceTab, QString());
        tabWidget_2->addTab(tripsTab, QString());
        souvenirsTab = new QWidget();
        souvenirsTab->setObjectName(QString::fromUtf8("souvenirsTab"));
        souvenirsTable = new QTableWidget(souvenirsTab);
        souvenirsTable->setObjectName(QString::fromUtf8("souvenirsTable"));
        souvenirsTable->setGeometry(QRect(40, 60, 501, 341));
        QFont font6;
        font6.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font6.setPointSize(9);
        souvenirsTable->setFont(font6);
        label_7 = new QLabel(souvenirsTab);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(30, 30, 151, 16));
        label_7->setFont(font1);
        totalPurchaseLabel = new QLabel(souvenirsTab);
        totalPurchaseLabel->setObjectName(QString::fromUtf8("totalPurchaseLabel"));
        totalPurchaseLabel->setGeometry(QRect(300, 420, 151, 16));
        totalPurchaseLabel->setFont(font1);
        totalPurchasePriceLabel = new QLabel(souvenirsTab);
        totalPurchasePriceLabel->setObjectName(QString::fromUtf8("totalPurchasePriceLabel"));
        totalPurchasePriceLabel->setGeometry(QRect(370, 410, 171, 31));
        QFont font7;
        font7.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font7.setPointSize(16);
        totalPurchasePriceLabel->setFont(font7);
        label_8 = new QLabel(souvenirsTab);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(40, 470, 161, 16));
        label_8->setFont(font1);
        makePurchaseList = new QListWidget(souvenirsTab);
        makePurchaseList->setObjectName(QString::fromUtf8("makePurchaseList"));
        makePurchaseList->setGeometry(QRect(40, 490, 311, 241));
        makePurchaseList->setFont(font6);
        purchaseButton = new QPushButton(souvenirsTab);
        purchaseButton->setObjectName(QString::fromUtf8("purchaseButton"));
        purchaseButton->setGeometry(QRect(370, 490, 191, 61));
        purchaseButton->setFont(font1);
        souvenirsErrorLabel = new QLabel(souvenirsTab);
        souvenirsErrorLabel->setObjectName(QString::fromUtf8("souvenirsErrorLabel"));
        souvenirsErrorLabel->setGeometry(QRect(370, 700, 191, 20));
        tabWidget_2->addTab(souvenirsTab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        randomButton = new QPushButton(tab_3);
        randomButton->setObjectName(QString::fromUtf8("randomButton"));
        randomButton->setGeometry(QRect(70, 80, 431, 51));
        QFont font8;
        font8.setFamily(QString::fromUtf8("Fixedsys"));
        randomButton->setFont(font8);
        randomDisplay = new QListWidget(tab_3);
        randomDisplay->setObjectName(QString::fromUtf8("randomDisplay"));
        randomDisplay->setGeometry(QRect(70, 210, 431, 221));
        randomDisplay->setFont(font3);
        label_25 = new QLabel(tab_3);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(70, 180, 151, 21));
        label_25->setFont(font1);
        tabWidget_2->addTab(tab_3, QString());
        redEdges = new QPushButton(tab);
        redEdges->setObjectName(QString::fromUtf8("redEdges"));
        redEdges->setGeometry(QRect(800, 820, 80, 25));
        singleEdge = new QPushButton(tab);
        singleEdge->setObjectName(QString::fromUtf8("singleEdge"));
        singleEdge->setGeometry(QRect(890, 820, 80, 25));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        addTeamStadiumLabel = new QLabel(tab_2);
        addTeamStadiumLabel->setObjectName(QString::fromUtf8("addTeamStadiumLabel"));
        addTeamStadiumLabel->setGeometry(QRect(500, 80, 461, 16));
        addTeamStadiumLabel->setFont(font1);
        modifySouvenirLabel = new QLabel(tab_2);
        modifySouvenirLabel->setObjectName(QString::fromUtf8("modifySouvenirLabel"));
        modifySouvenirLabel->setGeometry(QRect(1220, 80, 301, 16));
        modifySouvenirLabel->setFont(font1);
        line_2 = new QFrame(tab_2);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(960, 20, 20, 721));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        passwordBox = new QLineEdit(tab_2);
        passwordBox->setObjectName(QString::fromUtf8("passwordBox"));
        passwordBox->setGeometry(QRect(820, 770, 241, 41));
        passwordBox->setFont(font6);
        passwordBox->setEchoMode(QLineEdit::Password);
        enterPassLabel = new QLabel(tab_2);
        enterPassLabel->setObjectName(QString::fromUtf8("enterPassLabel"));
        enterPassLabel->setGeometry(QRect(820, 750, 261, 16));
        enterPassLabel->setFont(font2);
        line_3 = new QFrame(tab_2);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(10, 730, 1711, 20));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(tab_2);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(160, 110, 1431, 20));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        teamNameBox = new QLineEdit(tab_2);
        teamNameBox->setObjectName(QString::fromUtf8("teamNameBox"));
        teamNameBox->setGeometry(QRect(510, 620, 281, 41));
        teamNameBox->setFont(font6);
        stadiumBox = new QLineEdit(tab_2);
        stadiumBox->setObjectName(QString::fromUtf8("stadiumBox"));
        stadiumBox->setGeometry(QRect(510, 260, 391, 41));
        stadiumBox->setFont(font6);
        openDateBox = new QDateEdit(tab_2);
        openDateBox->setObjectName(QString::fromUtf8("openDateBox"));
        openDateBox->setGeometry(QRect(650, 440, 121, 41));
        QFont font9;
        font9.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font9.setPointSize(10);
        openDateBox->setFont(font9);
        label = new QLabel(tab_2);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(510, 600, 101, 16));
        label->setFont(font2);
        label_2 = new QLabel(tab_2);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(510, 240, 121, 16));
        label_2->setFont(font2);
        modifyStadiumInfoLabel = new QLabel(tab_2);
        modifyStadiumInfoLabel->setObjectName(QString::fromUtf8("modifyStadiumInfoLabel"));
        modifyStadiumInfoLabel->setGeometry(QRect(190, 150, 251, 16));
        modifyStadiumInfoLabel->setFont(font1);
        modifyTeamList = new QComboBox(tab_2);
        modifyTeamList->setObjectName(QString::fromUtf8("modifyTeamList"));
        modifyTeamList->setGeometry(QRect(190, 170, 731, 31));
        modifyTeamList->setFont(font6);
        adminStadiumInfo = new QListWidget(tab_2);
        adminStadiumInfo->setObjectName(QString::fromUtf8("adminStadiumInfo"));
        adminStadiumInfo->setGeometry(QRect(190, 260, 291, 181));
        adminStadiumInfo->setFont(font6);
        label_3 = new QLabel(tab_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(200, 240, 161, 16));
        label_3->setFont(font2);
        label_4 = new QLabel(tab_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(20, 20, 411, 16));
        QFont font10;
        font10.setFamily(QString::fromUtf8("Fixedsys"));
        font10.setPointSize(12);
        font10.setBold(true);
        font10.setWeight(75);
        label_4->setFont(font10);
        label_5 = new QLabel(tab_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(510, 580, 211, 16));
        label_5->setFont(font1);
        label_6 = new QLabel(tab_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(510, 220, 241, 16));
        label_6->setFont(font1);
        label_9 = new QLabel(tab_2);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(510, 300, 131, 20));
        label_9->setFont(font2);
        addressBox = new QLineEdit(tab_2);
        addressBox->setObjectName(QString::fromUtf8("addressBox"));
        addressBox->setGeometry(QRect(510, 320, 391, 41));
        addressBox->setFont(font6);
        label_10 = new QLabel(tab_2);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(510, 362, 55, 16));
        label_10->setFont(font2);
        cityBox = new QLineEdit(tab_2);
        cityBox->setObjectName(QString::fromUtf8("cityBox"));
        cityBox->setGeometry(QRect(510, 380, 171, 41));
        cityBox->setFont(font6);
        label_11 = new QLabel(tab_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(690, 363, 55, 16));
        label_11->setFont(font2);
        stateBox = new QLineEdit(tab_2);
        stateBox->setObjectName(QString::fromUtf8("stateBox"));
        stateBox->setGeometry(QRect(690, 380, 111, 41));
        stateBox->setFont(font6);
        capacityBox = new QSpinBox(tab_2);
        capacityBox->setObjectName(QString::fromUtf8("capacityBox"));
        capacityBox->setGeometry(QRect(510, 440, 131, 41));
        capacityBox->setFont(font9);
        capacityBox->setStepType(QAbstractSpinBox::DefaultStepType);
        label_12 = new QLabel(tab_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(510, 422, 91, 16));
        label_12->setFont(font2);
        label_13 = new QLabel(tab_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(650, 420, 101, 16));
        label_13->setFont(font2);
        label_14 = new QLabel(tab_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(510, 480, 121, 20));
        label_14->setFont(font2);
        latitudeBox = new QLineEdit(tab_2);
        latitudeBox->setObjectName(QString::fromUtf8("latitudeBox"));
        latitudeBox->setGeometry(QRect(510, 500, 111, 41));
        latitudeBox->setFont(font6);
        label_15 = new QLabel(tab_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(630, 482, 91, 16));
        label_15->setFont(font2);
        longitudeBox = new QLineEdit(tab_2);
        longitudeBox->setObjectName(QString::fromUtf8("longitudeBox"));
        longitudeBox->setGeometry(QRect(630, 500, 111, 41));
        longitudeBox->setFont(font6);
        zipBox = new QLineEdit(tab_2);
        zipBox->setObjectName(QString::fromUtf8("zipBox"));
        zipBox->setGeometry(QRect(810, 380, 91, 41));
        zipBox->setFont(font6);
        label_16 = new QLabel(tab_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(810, 363, 55, 16));
        label_16->setFont(font2);
        adminAddBox = new QPushButton(tab_2);
        adminAddBox->setObjectName(QString::fromUtf8("adminAddBox"));
        adminAddBox->setGeometry(QRect(690, 670, 101, 41));
        americanToggle = new QRadioButton(tab_2);
        americanToggle->setObjectName(QString::fromUtf8("americanToggle"));
        americanToggle->setGeometry(QRect(800, 620, 97, 22));
        americanToggle->setFont(font2);
        nationalToggle = new QRadioButton(tab_2);
        nationalToggle->setObjectName(QString::fromUtf8("nationalToggle"));
        nationalToggle->setGeometry(QRect(800, 640, 97, 22));
        nationalToggle->setFont(font2);
        label_17 = new QLabel(tab_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(781, 422, 55, 16));
        label_17->setFont(font2);
        grassBox = new QComboBox(tab_2);
        grassBox->setObjectName(QString::fromUtf8("grassBox"));
        grassBox->setGeometry(QRect(780, 440, 121, 41));
        modifyButton = new QPushButton(tab_2);
        modifyButton->setObjectName(QString::fromUtf8("modifyButton"));
        modifyButton->setGeometry(QRect(750, 550, 151, 41));
        label_18 = new QLabel(tab_2);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(750, 480, 55, 16));
        label_18->setFont(font2);
        phoneBox = new QLineEdit(tab_2);
        phoneBox->setObjectName(QString::fromUtf8("phoneBox"));
        phoneBox->setGeometry(QRect(750, 500, 151, 41));
        QFont font11;
        font11.setPointSize(9);
        phoneBox->setFont(font11);
        modifySouvenirList = new QComboBox(tab_2);
        modifySouvenirList->setObjectName(QString::fromUtf8("modifySouvenirList"));
        modifySouvenirList->setGeometry(QRect(1050, 173, 491, 31));
        label_19 = new QLabel(tab_2);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(1050, 150, 121, 16));
        label_19->setFont(font1);
        label_20 = new QLabel(tab_2);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(1050, 230, 55, 16));
        label_20->setFont(font2);
        souvNameBox = new QLineEdit(tab_2);
        souvNameBox->setObjectName(QString::fromUtf8("souvNameBox"));
        souvNameBox->setGeometry(QRect(1050, 250, 471, 51));
        souvNameBox->setFont(font11);
        souvPriceBox = new QDoubleSpinBox(tab_2);
        souvPriceBox->setObjectName(QString::fromUtf8("souvPriceBox"));
        souvPriceBox->setGeometry(QRect(1050, 330, 471, 51));
        souvPriceBox->setFont(font11);
        label_21 = new QLabel(tab_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(1050, 310, 55, 16));
        label_21->setFont(font8);
        modifySouvButton = new QPushButton(tab_2);
        modifySouvButton->setObjectName(QString::fromUtf8("modifySouvButton"));
        modifySouvButton->setGeometry(QRect(1050, 400, 231, 41));
        modifySouvButton->setFont(font1);
        addSouvButton = new QPushButton(tab_2);
        addSouvButton->setObjectName(QString::fromUtf8("addSouvButton"));
        addSouvButton->setGeometry(QRect(1289, 400, 111, 41));
        addSouvButton->setFont(font1);
        deleteSouvButton = new QPushButton(tab_2);
        deleteSouvButton->setObjectName(QString::fromUtf8("deleteSouvButton"));
        deleteSouvButton->setGeometry(QRect(1410, 400, 111, 41));
        deleteSouvButton->setFont(font1);
        adminPassError = new QLabel(tab_2);
        adminPassError->setObjectName(QString::fromUtf8("adminPassError"));
        adminPassError->setGeometry(QRect(820, 820, 241, 16));
        canadaBox = new QCheckBox(tab_2);
        canadaBox->setObjectName(QString::fromUtf8("canadaBox"));
        canadaBox->setGeometry(QRect(820, 230, 83, 22));
        adminStadiumError = new QLabel(tab_2);
        adminStadiumError->setObjectName(QString::fromUtf8("adminStadiumError"));
        adminStadiumError->setGeometry(QRect(514, 710, 461, 20));
        adminSouvError = new QLabel(tab_2);
        adminSouvError->setObjectName(QString::fromUtf8("adminSouvError"));
        adminSouvError->setGeometry(QRect(1050, 460, 471, 16));
        tabWidget->addTab(tab_2, QString());
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1809, 25));
        menuI_Love_Baseball = new QMenu(menuBar);
        menuI_Love_Baseball->setObjectName(QString::fromUtf8("menuI_Love_Baseball"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuI_Love_Baseball->menuAction());

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);
        tabWidget_2->setCurrentIndex(1);
        tabWidget_3->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        clearMap->setText(QCoreApplication::translate("MainWindow", "Clear Map", nullptr));
        errorLabel->setText(QString());
        addMarkers->setText(QCoreApplication::translate("MainWindow", "Add Markers", nullptr));
        addEdges->setText(QCoreApplication::translate("MainWindow", "Add Edges", nullptr));
        stadiumInfoLabel->setText(QCoreApplication::translate("MainWindow", "STADIUM INFO", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(stadiumInfoTab), QCoreApplication::translate("MainWindow", "Stadium Info", nullptr));
        planTripLabel->setText(QCoreApplication::translate("MainWindow", "TRIP PLANNING", nullptr));
        itineraryLabel->setText(QCoreApplication::translate("MainWindow", "ITINERARY", nullptr));
        displayMajorLeagueTrip->setText(QCoreApplication::translate("MainWindow", "ALL MAJOR LEAGUE STADIUMS (FROM CA)", nullptr));
        whereDoYouWantToGoLabel->setText(QCoreApplication::translate("MainWindow", "WHERE DO YOU WANT TO GO?", nullptr));
        displayNationalLeagueTrip->setText(QCoreApplication::translate("MainWindow", "ALL NATIONAL LEAGUE STADIUMS  (FROM CA)", nullptr));
        displayAmericanLeagueTrip->setText(QCoreApplication::translate("MainWindow", "ALL AMERICAN LEAGUE STADIUMS (FROM CA)", nullptr));
        safecoButton->setText(QCoreApplication::translate("MainWindow", "SAFECO", nullptr));
        tabWidget_3->setTabText(tabWidget_3->indexOf(presetTab), QCoreApplication::translate("MainWindow", "Preset Trips", nullptr));
        letsTravel->setText(QCoreApplication::translate("MainWindow", "LET'S TRAVEL", nullptr));
        chooseDestinationsLabel->setText(QCoreApplication::translate("MainWindow", "CHOOSE YOUR DESTINATIONS", nullptr));
        destinationsListLabel->setText(QCoreApplication::translate("MainWindow", "DESTINATIONS LIST", nullptr));
        addStadiumToTrip->setText(QCoreApplication::translate("MainWindow", "ADD TO DESTINATIONS", nullptr));
        clearDestinationList->setText(QCoreApplication::translate("MainWindow", "CLEAR LIST", nullptr));
        planATripErrorLabel->setText(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(planATripTab), QCoreApplication::translate("MainWindow", "Plan A Trip", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "FIND STADIUM DISTANCE", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "STADIUM A", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "STADIUM B", nullptr));
        distanceButton->setText(QCoreApplication::translate("MainWindow", "FIND DISTANCE", nullptr));
        distanceLabel->setText(QString());
        tabWidget_3->setTabText(tabWidget_3->indexOf(findDistanceTab), QCoreApplication::translate("MainWindow", "Distances", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tripsTab), QCoreApplication::translate("MainWindow", "Trips", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "SOUVENIRS", nullptr));
        totalPurchaseLabel->setText(QCoreApplication::translate("MainWindow", "TOTAL", nullptr));
        totalPurchasePriceLabel->setText(QString());
        label_8->setText(QCoreApplication::translate("MainWindow", "MAKE PURCHASES", nullptr));
        purchaseButton->setText(QCoreApplication::translate("MainWindow", "PURCHASE", nullptr));
        souvenirsErrorLabel->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(souvenirsTab), QCoreApplication::translate("MainWindow", "Souvenirs", nullptr));
        randomButton->setText(QCoreApplication::translate("MainWindow", "TAKE ME SOMEWHERE NEW", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "STADIUM INFO", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_3), QCoreApplication::translate("MainWindow", "Randomize!", nullptr));
        redEdges->setText(QCoreApplication::translate("MainWindow", "Red Edges", nullptr));
        singleEdge->setText(QCoreApplication::translate("MainWindow", "Single Edge", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("MainWindow", "Map/Plan A Trip", nullptr));
        addTeamStadiumLabel->setText(QCoreApplication::translate("MainWindow", "TEAM/STADIUMS", nullptr));
        modifySouvenirLabel->setText(QCoreApplication::translate("MainWindow", "SOUVENIRS", nullptr));
        enterPassLabel->setText(QCoreApplication::translate("MainWindow", "ENTER ADMIN PASSWORD", nullptr));
        teamNameBox->setPlaceholderText(QCoreApplication::translate("MainWindow", "New Team Name", nullptr));
        stadiumBox->setPlaceholderText(QCoreApplication::translate("MainWindow", "Stadium Name", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "TEAM NAME", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "STADIUM NAME", nullptr));
        modifyStadiumInfoLabel->setText(QCoreApplication::translate("MainWindow", "TEAM", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "STADIUM INFO", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "ADMINISTRATOR MODE", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "ADD NEW TEAM", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "STADIUM CONFIG", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "ADDRESS", nullptr));
        addressBox->setPlaceholderText(QCoreApplication::translate("MainWindow", "Street Name & Number", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "CITY", nullptr));
        cityBox->setPlaceholderText(QCoreApplication::translate("MainWindow", "City", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "STATE", nullptr));
        stateBox->setPlaceholderText(QCoreApplication::translate("MainWindow", "State", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "CAPACITY", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "OPEN DATE", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "LATITUDE", nullptr));
        latitudeBox->setPlaceholderText(QCoreApplication::translate("MainWindow", "Latitude", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "LONGITUDE", nullptr));
        longitudeBox->setPlaceholderText(QCoreApplication::translate("MainWindow", "Longitude", nullptr));
        zipBox->setPlaceholderText(QCoreApplication::translate("MainWindow", "Zip Code", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "ZIP", nullptr));
        adminAddBox->setText(QCoreApplication::translate("MainWindow", "ADD", nullptr));
        americanToggle->setText(QCoreApplication::translate("MainWindow", "AMERICAN", nullptr));
        nationalToggle->setText(QCoreApplication::translate("MainWindow", "NATIONAL", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "GRASS?", nullptr));
        modifyButton->setText(QCoreApplication::translate("MainWindow", "MAKE CHANGES", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "PHONE", nullptr));
        phoneBox->setPlaceholderText(QCoreApplication::translate("MainWindow", "10 digits, no spaces", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "SOUVENIR", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "NAME", nullptr));
        souvNameBox->setPlaceholderText(QCoreApplication::translate("MainWindow", "Souvenir Name", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "PRICE", nullptr));
        modifySouvButton->setText(QCoreApplication::translate("MainWindow", "MODIFY", nullptr));
        addSouvButton->setText(QCoreApplication::translate("MainWindow", "ADD", nullptr));
        deleteSouvButton->setText(QCoreApplication::translate("MainWindow", "DELETE", nullptr));
        adminPassError->setText(QString());
        canadaBox->setText(QCoreApplication::translate("MainWindow", "CANADA", nullptr));
        adminStadiumError->setText(QString());
        adminSouvError->setText(QString());
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("MainWindow", "Admin", nullptr));
        menuI_Love_Baseball->setTitle(QCoreApplication::translate("MainWindow", "I Love Baseball!", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
